version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: registry.rom1.xyz/tournoififa_web:latest
    command: gunicorn tournoi_fifa.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
        - DEBUG=0
        - DJANGO_ALLOWED_HOSTS=fifa-covid19.be
        - SQL_ENGINE=django.db.backends.postgresql
        - SQL_DATABASE=tournoi_fifa
        - SQL_USER=covid19
        - SQL_HOST=db
        - SQL_PORT=5432
        - DATABASE=postgres
    depends_on:
      - db
    networks:
      - private
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    environment:
        - POSTGRES_USER=covid19
        - POSTGRES_DB=tournoi_fifa
    networks:
      - private
  nginx:
    build: ./nginx
    image: registry.rom1.xyz/tournoififa_nginx:latest
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web
    deploy:
      labels:
        - traefik.frontend.rule=Host:fifa-covid19.be
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=public
        - traefik.docker.network=public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    networks:
      - private
      - public

networks:
  private:
    driver: overlay
  public:
    external: true

volumes:
  postgres_data:
  static_volume:
